import Background from "@/components/atoms/Background";
import NavigationBar from "@/components/molecules/NavigationBar";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lightning bowling",
  description: "Generated by lightning bowling",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <link rel="icon" href="/favicons/favicon.ico" />
      </head>
      <body>
        <NavigationBar />
        <Background>{children}</Background>
      </body>
    </html>
  );
}
