import "@/styles/globals.css"
import type { Metadata } from "next"
import Link from "next/link"
import Background from "@/components/atoms/Background";
import NavigationBar from "@/components/molecules/NavigationBar";

export const metadata: Metadata = {
  title: "Lightning bowling",
  description: "Generated by lightning bowling",
}

export default function RootLayout(props: { children: React.ReactNode; modal: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="bg-[#F6F6F6]">
        <head>
        <link rel="icon" href="/favicons/favicon.ico" />
        </head>
        <header className="flex justify-between items-center bg-gray-800 text-white p-4">
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="/">홈</Link>
              </li>
              <li>
                <Link href="/signup">회원가입</Link>
              </li>
              <li>
                <Link href="/signin">로그인</Link>
              </li>
            </ul>
          </nav>
        </header>
        <NavigationBar />
        <Background>{props.children}</Background>
        {props.modal}
      </body>
    </html>
  )
}
